import type { Metadata } from "next";
import { Ubuntu, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";


const ubuntu = Ubuntu({
  subsets: ["latin"],
  variable: "--font-ubuntu",
  weight: ['400', '500', '700'], // Specify font weights (optional)
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${ubuntu.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
